server: 
    port: 8082
    servlet:
        context-path: /ui
        session: 
            cookie: 
                name: UISESSION



spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
        client:
          registration:
            custom-client:
                client-id: clientId
                client-secret: secret
                client-name: Auth Server
                scope: user_info
                provider: custom-provider
                redirect-uri-template: http://localhost:8083/login/oauth2/code/
                client-authentication-method: basic
                authorization-grant-type: authorization_code
          provider:
            custom-provider:
                token-uri: http://localhost:8083/auth/oauth/token
                authorization-uri: http://localhost:8083/auth/oauth/authorize
                user-info-uri: http://localhost:8083/auth/user/me
                user-name-attribute: name
     